### PR TITLE
fix: catch error when user use OTP has been used before..

### PR DESCRIPTION
**Pull request by minatisleeping**

### CODE REVIEW

**Review by hoangday185 — APPROVED** [review]
good

**Review by lcaohoanq — COMMENTED** [review]
May you can add any image, video for proof this feature work

**Comment by minatisleeping** [comment]
@lcaohoanq ýe, pls read comment on [this ticket](https://github.com/orgs/PiedTeam/projects/7/views/7?pane=issue&itemId=65652177)..

**Comment by lcaohoanq** [comment]
> @lcaohoanq ýe, pls read comment on [this ticket](https://github.com/orgs/PiedTeam/projects/7/views/7?pane=issue&itemId=65652177)..

Thanks, i have missed this info

**Pull request merged**
