### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Buicongbang04**
I have create feature register and login with google. Please, review it for me. Thank you very much.

### CODE REVIEW

**Review by minatisleeping — COMMENTED** [review]
perfect conflict

**Review by minatisleeping — COMMENTED** [review]
nice

**Review by minatisleeping — COMMENTED** [review]
nice

**Review by BLonggg608 — APPROVED** [review]

**Review by minatisleeping — APPROVED** [review]

**Review by LeHoDiep — COMMENTED** [review]
revewed

**Pull request merged**
